### PR TITLE
Add getting/deletion/saving of typed documents for collections

### PR DESCRIPTION
**Pull request by yajo10**

### CODE REVIEW

**Comment by LowLevelSubmarine** [comment]
Wow very nice! Is this working already on your branch?

**Comment by LowLevelSubmarine** [comment]
Does it also solve #525?

**Comment by LowLevelSubmarine** [comment]
Will try your branch out, asap

**Comment by yajo10** [comment]
@blaugold any chance, that you can give me some feedback on this? Do you plan to integrate this?

**Comment by blaugold** [comment]
@yajo10 Sorry for the late response! I'll look at it today.

**Comment by yajo10** [comment]
@blaugold Thank you very much for taking your time to look into this. Yes, I'm currently using this branch. That's also the reason why I did not update for the current master but just for the most recent version. 
If you want me to test something, just let me know.

**Comment by blaugold** [comment]
I've just published a prerelease with support for typed documents in collections:

```
Package Name                            
cbl                                   3.3.0-dev.0
cbl_dart                              3.2.0-dev.0
cbl_generator                         0.3.1-dev.0
cbl_flutter_platform_interface        3.1.0-dev.0
cbl_flutter                           3.2.0-dev.0
cbl_flutter_ce                        3.3.0-dev.0
cbl_flutter_ee                        3.3.0-dev.0
cbl_sentry                            2.1.2-dev.0
```

@yajo10 If you can, please try it out and let me know if there are any issues. Thanks!

**Comment by blaugold** [comment]
Never mind, the current prerelease is broken. Once I have published a fix, I'll post an update.

**Comment by blaugold** [comment]
The following versions should work now. Happy testing. 🧪😊

```
Package Name                            
cbl                                   3.3.0-dev.0
cbl_dart                              3.2.0-dev.0
cbl_generator                         0.3.1-dev.0
cbl_flutter_platform_interface        3.1.0-dev.0
cbl_flutter                           3.2.0-dev.1
cbl_flutter_ce                        3.3.0-dev.2
cbl_flutter_ee                        3.3.0-dev.2
cbl_sentry                            2.1.2-dev.0
```

**Comment by blaugold** [comment]
I'm closing this PR since it was superseded by #650.

**Comment by blaugold** [comment]
Can run `flutter clean` and then try again?

**Comment by blaugold** [comment]
And please ensure you are using version `3.3.0-dev.2` of `cbl_flutter_ce`!

**Comment by yajo10** [comment]
I tried, but there is still the same error. I can show you the pubspec.yaml:

```
name: sample
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.3.5+19

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.24.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2


  cupertino_icons: ^1.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  flutter_map_location_marker: any # or latest verion
  flutter_map_animations: ^0.7.1
  flutter_map_geojson: ^1.0.5
  flutter_map_marker_popup: any
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  glassmorphism: ^3.0.0
  flutter_offline: ^4.0.0
  connectivity_plus: ^6.1.0
  listview_utils_plus: ^0.0.3
  intl: ^0.19.0
  glassmorphism_widgets: ^0.2.2
  flutter_map_tile_caching: ^9.0.0-dev.5
  get_it: ^8.0.2
  flutter_launcher_icons: ^0.14.1
  grouped_list: ^6.0.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.4
  fading_edge_scrollview: ^4.0.0
  cbl: ^3.3.0-dev.0
  cbl_flutter: ^3.2.0-dev.1
  cbl_flutter_ce: ^3.3.0-dev.2
  uuid: ^4.3.2
  oidc: ^0.7.0
  oidc_default_store: ^0.2.0+8
  http: ^1.2.0
  app_links: ^6.3.2
  dart_jsonwebtoken: ^2.14.0
  flutter_rating: ^2.0.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lints: ^4.0.0
  cbl_generator: ^0.3.1-dev.0
  build_runner: ^2.4.8

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/geo/peaks.geojson
    - lib/assets/images/background.jpg
    - lib/assets/images/background-square.jpg
    - lib/assets/icon/icon.jpg



  # This package implements the icons: https://pub.dev/packages/flutter_launcher_icons
  # Use the following commant to re-generate the icons: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/icon/icon-without-background.png"
  image_path: "lib/assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

```

**Comment by blaugold** [comment]
OK, I've published a new round of versions that should fix the build issue. 🤞

```
Package Name
cbl                                   3.3.0-dev.1
cbl_flutter                           3.2.0-dev.2
cbl_flutter_ce                        3.3.0-dev.3
cbl_flutter_ee                        3.3.0-dev.3
cbl_dart                              3.2.0-dev.1
cbl_generator                         0.3.1-dev.1
cbl_sentry                            2.1.2-dev.1
```

Please also run `dart pub global deactivate cbl_flutter` and `flutter clean` before trying the new versions.

**Comment by yajo10** [comment]
Sorry, it is still not working for me. Right now, I'm getting this error, when I run `flutter build apk --verbose --debug`: 

```
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'cbl_flutter_install'
[        ]      at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
[        ]      at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
[        ]      at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
[        ]      at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
[        ]      ... 6 more
[        ] Caused by: java.io.IOException: Cannot run program "cbl_flutter_install" (in directory "/home/sample/.pub-cache/hosted/pub.dev/cbl_flutter_ce-3.3.0-dev.3"): error=2, Datei oder Verzeichnis nicht gefunden

```

**Comment by blaugold** [comment]
No problem! Thank you for testing! Could you give version `3.3.0-dev.4` of `cbl_flutter_ce` a try?

**Comment by yajo10** [comment]
It is still not working, but now I get a different error message:

```
[ +468 ms] > Task :cbl_flutter_ce:installLibraries FAILED
[        ] Caching disabled for task ':cbl_flutter_ce:installLibraries' because:
[        ]   Build cache is disabled
[        ] Task ':cbl_flutter_ce:installLibraries' is not up-to-date because:
[        ]   Task has not declared any outputs despite executing actions.
[        ] Starting process 'command 'dart''. Working directory: /home/amundsen/.pub-cache/hosted/pub.dev/cbl_flutter_ce-3.3.0-dev.4 Command: dart pub global run cbl_flutter_install android
[        ] Successfully started process 'command 'dart''
[        ] :cbl_flutter_ce:installLibraries (Thread[Execution worker Thread 7,5,main]) completed. Took 2.351 secs.
[        ] Unhandled exception:
[   +2 ms] FileSystemException: Rename failed, path = '/tmp/SHGHRS' (OS Error: Invalid cross-device link, errno = 18)
[        ] #0      _checkForErrorResponse (dart:io/common.dart:55:9)
[        ] #1      _Directory.rename.<anonymous closure> (dart:io/directory_impl.dart:195:7)
[        ] <asynchronous suspension>
[        ] #2      moveDirectory (package:cbl/src/install/utils.dart:171:3)
[        ] <asynchronous suspension>
[        ] #3      RemotePackageLoader._packageDir (package:cbl/src/install/package.dart:292:9)
[        ] <asynchronous suspension>
[        ] #4      PackageLoader.load (package:cbl/src/install/package.dart:256:23)
[        ] <asynchronous suspension>
[        ] #5      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
[        ] <asynchronous suspension>
[        ] #6      main (file:///home/amundsen/.pub-cache/hosted/pub.dev/cbl_flutter_install-0.1.0-dev.1/bin/cbl_flutter_install.dart:43:20)
[        ] <asynchronous suspension>

```

**Comment by blaugold** [comment]
@yajo10 I should have a fix for this in cbl_flutter_ce: `^3.3.0-dev.5`

**Comment by yajo10** [comment]
@blaugold Yes, thank you very much for your work. Now it's working 👍

**Pull request closed without merging**
