### PR TITLE
feat: add support for collections

### PR DESCRIPTION
**Pull request by blaugold**
- [x] Document adding collections to `ReplicatorConfiguration`
- [x] Add tests for `Replicator` collection APIs

### CODE REVIEW

**Comment by LowLevelSubmarine** [comment]
We are planning to use collections with out flutter app before we hit production, so that we dont have to migrate from the _default collection (if this is even possible). Will work continue on this feature branch in the near future?

**Comment by blaugold** [comment]
@LowLevelSubmarine This branch is basically ready to be merged. What's missing is updating the docs, but I'll do that in another PR and go ahead and publish a pre-release with support for collections. That way you can start using them. Once the docs are updated, I'll publish a stable release.

**Comment by LowLevelSubmarine** [comment]
This is awesome, thank you very much!

**Comment by LowLevelSubmarine** [comment]
Could you leave a comment here when the pre-release is available?

**Comment by blaugold** [comment]
> Could you leave a comment here when the pre-release is available?

I'm planning to publish the pre-release tomorrow, but I'll give an update here when it's actually available.

**Comment by blaugold** [comment]
The pre-release is now available on pub.dev. All the packages are currently at `3.0.0-dev.1`.

**Pull request merged**
